// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oopqqcppougeggbqvhor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcHFxY3Bwb3VnZWdnYnF2aG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzU1NjYsImV4cCI6MjA2Njk1MTU2Nn0.Pm5_qiVmF920JdruY0cnQLDboJ42v1Ce0cCIu_9DqX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});